Enhance `LibraryClassifier` to track library versions and replace older versions with newer ones.
the loader always throws a `NoSuchMethodError` or `NoClassDefFoundError` when the plugin downloads a different version of a library. (for example, MythicMob. they use kyori-component 4.16 which was released 3 years ago!!!)